version: 2
updates:
  # Enable dependency updates
  - package-ecosystem: "npm"
    directory: "/"
    # Check the npm registry for updates once a week
    schedule:
      interval: "weekly"
    # The following is required for workspaces to be updated: see https://github.com/dependabot/dependabot-core/issues/5226.
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "npm"
    ignore:
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typedoc-plugin-markdown"
        update-types: ["version-update:semver-major"]
    groups:
      internal-tooling:
        patterns:
          - "@inrupt/internal-*"
          - "@inrupt/base-*"
          - "@inrupt/jest-*"
          - "@inrupt/eslint-*"
      external-types:
        patterns:
          - "@types/*"

  # Enable version updates for the website tooling
  - package-ecosystem: "pip"
    directory: "/docs"
    # Check the npm registry for updates once a week
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "pip"
  # Enable version updates for our CI tooling
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check the npm registry for updates once a week
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
